import type { SessionStatus, UserRole } from "../../domain/evalora.types";
import type { SystemHealthDto } from "../analytics/system-health.service";

export type SubscriptionPlanDto = "free" | "pro" | "enterprise";
export type AdminAccountStatus = "active" | "suspended";
export type AdminSortOrder = "asc" | "desc";
export type AdminOrganizationSort = "createdAt" | "name" | "sessions";
export type AdminUserSort = "createdAt" | "name" | "email";

export interface AdminPageDto<T> {
  items: T[];
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

export interface AdminOrganizationDto {
  id: string;
  name: string;
  plan: SubscriptionPlanDto;
  isSuspended: boolean;
  suspendedAt?: string;
  createdAt: string;
  updatedAt: string;
  /** Earliest owner-role member; absent for a workspace whose owner was removed. */
  owner?: { id: string; name: string; email: string };
  /** Staff attached to the workspace: owners, interviewers, and platform admins. Candidate records never count. */
  memberCount: number;
  sessionCount: number;
  templateCount: number;
  /** True when the acting admin belongs to this workspace, which the UI uses to disable self-suspension. */
  isCurrentWorkspace: boolean;
}

export interface AdminUserDto {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  roleLabel: string;
  emailVerified: boolean;
  isSuspended: boolean;
  suspendedAt?: string;
  createdAt: string;
  organization?: { id: string; name: string; isSuspended: boolean };
  isCurrentUser: boolean;
}

export interface UsageWindow {
  allTime: number;
  thisMonth: number;
}

/** Two equal-length windows so a change can be read as a percentage; `changePct` is null when there is no baseline. */
export interface ComparisonDto {
  current: number;
  previous: number;
  changePct: number | null;
}

/** Daily counts for the last 30 UTC days. Every array is aligned with `days`, oldest first, ending today. */
export interface ActivitySeriesDto {
  days: string[];
  sessionsStarted: number[];
  sessionsCompleted: number[];
  newUsers: number[];
  newOrganizations: number[];
  billableTurns: number[];
}

/** Things an operator is expected to act on, each linkable to a filtered list. */
export interface AdminAttentionDto {
  suspendedOrganizations: number;
  suspendedUsers: number;
  /** Owners, interviewers, and admins who never verified their email. */
  unverifiedStaff: number;
  /** Workspaces with no owner-role account left. */
  workspacesWithoutOwner: number;
  liveSessions: number;
}

export interface AdminOverviewDto {
  asOf: string;
  /** Start of the calendar month (UTC) every `thisMonth` figure is measured from. */
  monthStart: string;
  activity: ActivitySeriesDto;
  /** Last 30 days against the 30 days before that. */
  comparisons: {
    sessionsStarted: ComparisonDto;
    sessionsCompleted: ComparisonDto;
    newUsers: ComparisonDto;
    newOrganizations: ComparisonDto;
    billableTurns: ComparisonDto;
  };
  attention: AdminAttentionDto;
  organizations: {
    total: number;
    active: number;
    suspended: number;
    newThisMonth: number;
    byPlan: Record<SubscriptionPlanDto, number>;
    /** Non-suspended workspaces on a paid plan. */
    paidSubscriptions: number;
  };
  users: {
    total: number;
    suspended: number;
    newThisMonth: number;
    byRole: Record<UserRole, number>;
  };
  sessions: {
    total: number;
    thisMonth: number;
    completedThisMonth: number;
    live: number;
    byStatus: Record<SessionStatus, number>;
  };
  ai: {
    provider: "deepseek" | "fallback";
    model?: string;
    costPerTurnUsd: number;
    /** Every assistant turn persisted for candidate interviews, whichever provider produced it. */
    interviewTurns: UsageWindow;
    /** Assistant turns the configured model actually generated (fallback turns cost nothing). */
    billableTurns: UsageWindow;
    /** AI-assisted template drafts generated by the configured model. */
    draftGenerations: UsageWindow;
    estimatedCostUsd: UsageWindow;
    /** Month-to-date cost extrapolated linearly over the calendar month. */
    projectedMonthCostUsd: number;
    methodology: string;
  };
  systemHealth: SystemHealthDto;
}

export interface AdminSessionSummaryDto {
  id: string;
  title?: string;
  candidateName: string;
  templateTitle: string;
  status: SessionStatus;
  createdAt: string;
  completedAt?: string;
}

export interface AdminOrganizationMemberDto {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  roleLabel: string;
  emailVerified: boolean;
  isSuspended: boolean;
  createdAt: string;
}

export interface AdminOrganizationDetailDto extends AdminOrganizationDto {
  members: AdminOrganizationMemberDto[];
  sessionsByStatus: Record<SessionStatus, number>;
  recentSessions: AdminSessionSummaryDto[];
  draftCount: number;
  /** Most recent session update in the workspace, if any. */
  lastActivityAt?: string;
}

export interface AdminUserDetailDto extends AdminUserDto {
  updatedAt: string;
  createdSessionCount: number;
  candidateSessionCount: number;
  templateCount: number;
  /** Sessions this account created or sat, most recently updated first. */
  recentSessions: AdminSessionSummaryDto[];
  lastActivityAt?: string;
}
