import type { SessionStatus, UserRole } from "../../domain/evalora.types";
import type { SystemHealthDto } from "../analytics/system-health.service";

export type SubscriptionPlanDto = "free" | "pro" | "enterprise";
export type AdminAccountStatus = "active" | "suspended";

export interface AdminPageDto<T> {
  items: T[];
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

export interface AdminOrganizationDto {
  id: string;
  name: string;
  plan: SubscriptionPlanDto;
  isSuspended: boolean;
  suspendedAt?: string;
  createdAt: string;
  updatedAt: string;
  /** Earliest owner-role member; absent for a workspace whose owner was removed. */
  owner?: { id: string; name: string; email: string };
  /** Owners + interviewers. Candidate records never count as members. */
  memberCount: number;
  sessionCount: number;
  templateCount: number;
  /** True when the acting admin belongs to this workspace, which the UI uses to disable self-suspension. */
  isCurrentWorkspace: boolean;
}

export interface AdminUserDto {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  roleLabel: string;
  emailVerified: boolean;
  isSuspended: boolean;
  suspendedAt?: string;
  createdAt: string;
  organization?: { id: string; name: string; isSuspended: boolean };
  isCurrentUser: boolean;
}

export interface UsageWindow {
  allTime: number;
  thisMonth: number;
}

export interface AdminOverviewDto {
  asOf: string;
  /** Start of the calendar month (UTC) every `thisMonth` figure is measured from. */
  monthStart: string;
  organizations: {
    total: number;
    active: number;
    suspended: number;
    newThisMonth: number;
    byPlan: Record<SubscriptionPlanDto, number>;
    /** Non-suspended workspaces on a paid plan. */
    paidSubscriptions: number;
  };
  users: {
    total: number;
    suspended: number;
    newThisMonth: number;
    byRole: Record<UserRole, number>;
  };
  sessions: {
    total: number;
    thisMonth: number;
    completedThisMonth: number;
    live: number;
    byStatus: Record<SessionStatus, number>;
  };
  ai: {
    provider: "deepseek" | "fallback";
    model?: string;
    costPerTurnUsd: number;
    /** Every assistant turn persisted for candidate interviews, whichever provider produced it. */
    interviewTurns: UsageWindow;
    /** Assistant turns the configured model actually generated (fallback turns cost nothing). */
    billableTurns: UsageWindow;
    /** AI-assisted template drafts generated by the configured model. */
    draftGenerations: UsageWindow;
    estimatedCostUsd: UsageWindow;
    methodology: string;
  };
  systemHealth: SystemHealthDto;
}
