import type { CodeQuestion } from "../interfaces/code.interfaces";
import type { CodeLanguage } from "../types/code.types";

export const SUPPORTED_CODE_LANGUAGES = ["javascript", "typescript", "python", "java"] as const satisfies readonly CodeLanguage[];

// Guardrails for untrusted candidate input submitted to the execution sandbox.
// Source is capped well below Express' default 100kb JSON body limit; stdin is
// smaller still since it only feeds a single test case.
export const MAX_SOURCE_CODE_LENGTH = 64_000;
export const MAX_STDIN_LENGTH = 16_000;

// NOTE: This file is generated by scripts/gen-questions. Expected outputs were
// produced by running reference solutions through Piston, so they are verified.
export const CODE_QUESTIONS: CodeQuestion[] = [
  {
    "id": "sum-two-numbers",
    "title": "Sum Two Numbers",
    "description": "Read two integers from stdin (space-separated) and print their sum.",
    "difficulty": "easy",
    "starterCode": "// Sum Two Numbers\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "2 3",
    "sampleOutput": "5\n",
    "testCases": [
      {
        "stdin": "10 -4",
        "expectedOutput": "6\n"
      },
      {
        "stdin": "100 250",
        "expectedOutput": "350\n"
      },
      {
        "stdin": "-7 -8",
        "expectedOutput": "-15\n"
      }
    ]
  },
  {
    "id": "max-of-three",
    "title": "Maximum of Three",
    "description": "Read three integers (space-separated) and print the largest.",
    "difficulty": "easy",
    "starterCode": "// Maximum of Three\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "3 9 5",
    "sampleOutput": "9\n",
    "testCases": [
      {
        "stdin": "-1 -5 -3",
        "expectedOutput": "-1\n"
      },
      {
        "stdin": "7 7 2",
        "expectedOutput": "7\n"
      },
      {
        "stdin": "42 42 42",
        "expectedOutput": "42\n"
      }
    ]
  },
  {
    "id": "even-or-odd",
    "title": "Even or Odd",
    "description": "Read an integer n and print \"Even\" if it is even, otherwise \"Odd\".",
    "difficulty": "easy",
    "starterCode": "// Even or Odd\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "4",
    "sampleOutput": "Even\n",
    "testCases": [
      {
        "stdin": "7",
        "expectedOutput": "Odd\n"
      },
      {
        "stdin": "0",
        "expectedOutput": "Even\n"
      },
      {
        "stdin": "-3",
        "expectedOutput": "Odd\n"
      }
    ]
  },
  {
    "id": "sum-to-n",
    "title": "Sum From 1 to N",
    "description": "Read a non-negative integer n and print the sum 1 + 2 + ... + n.",
    "difficulty": "easy",
    "starterCode": "// Sum From 1 to N\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "5",
    "sampleOutput": "15\n",
    "testCases": [
      {
        "stdin": "10",
        "expectedOutput": "55\n"
      },
      {
        "stdin": "1",
        "expectedOutput": "1\n"
      },
      {
        "stdin": "100",
        "expectedOutput": "5050\n"
      }
    ]
  },
  {
    "id": "factorial",
    "title": "Factorial",
    "description": "Read a non-negative integer n and print n! (n factorial). 0! is 1.",
    "difficulty": "easy",
    "starterCode": "// Factorial\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "5",
    "sampleOutput": "120\n",
    "testCases": [
      {
        "stdin": "0",
        "expectedOutput": "1\n"
      },
      {
        "stdin": "6",
        "expectedOutput": "720\n"
      },
      {
        "stdin": "10",
        "expectedOutput": "3628800\n"
      }
    ]
  },
  {
    "id": "reverse-string",
    "title": "Reverse a String",
    "description": "Read a single word and print it reversed.",
    "difficulty": "easy",
    "starterCode": "// Reverse a String\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "hello",
    "sampleOutput": "olleh\n",
    "testCases": [
      {
        "stdin": "world",
        "expectedOutput": "dlrow\n"
      },
      {
        "stdin": "abc",
        "expectedOutput": "cba\n"
      },
      {
        "stdin": "racecar",
        "expectedOutput": "racecar\n"
      }
    ]
  },
  {
    "id": "count-vowels",
    "title": "Count Vowels",
    "description": "Read a word and print how many vowels (a, e, i, o, u) it contains. Case-insensitive.",
    "difficulty": "easy",
    "starterCode": "// Count Vowels\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "programming",
    "sampleOutput": "3\n",
    "testCases": [
      {
        "stdin": "aeiou",
        "expectedOutput": "5\n"
      },
      {
        "stdin": "xyz",
        "expectedOutput": "0\n"
      },
      {
        "stdin": "Banana",
        "expectedOutput": "3\n"
      }
    ]
  },
  {
    "id": "absolute-difference",
    "title": "Absolute Difference",
    "description": "Read two integers (space-separated) and print the absolute value of their difference.",
    "difficulty": "easy",
    "starterCode": "// Absolute Difference\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "10 4",
    "sampleOutput": "6\n",
    "testCases": [
      {
        "stdin": "4 10",
        "expectedOutput": "6\n"
      },
      {
        "stdin": "-5 5",
        "expectedOutput": "10\n"
      },
      {
        "stdin": "0 0",
        "expectedOutput": "0\n"
      }
    ]
  },
  {
    "id": "nth-fibonacci",
    "title": "Nth Fibonacci Number",
    "description": "Read a non-negative integer n and print the n-th Fibonacci number (F(0)=0, F(1)=1).",
    "difficulty": "medium",
    "starterCode": "// Nth Fibonacci Number\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "7",
    "sampleOutput": "13\n",
    "testCases": [
      {
        "stdin": "0",
        "expectedOutput": "0\n"
      },
      {
        "stdin": "1",
        "expectedOutput": "1\n"
      },
      {
        "stdin": "10",
        "expectedOutput": "55\n"
      }
    ]
  },
  {
    "id": "is-prime",
    "title": "Prime Check",
    "description": "Read an integer n and print \"Yes\" if it is prime, otherwise \"No\".",
    "difficulty": "medium",
    "starterCode": "// Prime Check\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "7",
    "sampleOutput": "Yes\n",
    "testCases": [
      {
        "stdin": "1",
        "expectedOutput": "No\n"
      },
      {
        "stdin": "12",
        "expectedOutput": "No\n"
      },
      {
        "stdin": "13",
        "expectedOutput": "Yes\n"
      },
      {
        "stdin": "2",
        "expectedOutput": "Yes\n"
      }
    ]
  },
  {
    "id": "gcd",
    "title": "Greatest Common Divisor",
    "description": "Read two positive integers (space-separated) and print their greatest common divisor.",
    "difficulty": "medium",
    "starterCode": "// Greatest Common Divisor\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "12 18",
    "sampleOutput": "6\n",
    "testCases": [
      {
        "stdin": "17 5",
        "expectedOutput": "1\n"
      },
      {
        "stdin": "100 40",
        "expectedOutput": "20\n"
      },
      {
        "stdin": "7 7",
        "expectedOutput": "7\n"
      }
    ]
  },
  {
    "id": "palindrome",
    "title": "Palindrome Check",
    "description": "Read a word and print \"Yes\" if it reads the same forwards and backwards, otherwise \"No\".",
    "difficulty": "medium",
    "starterCode": "// Palindrome Check\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "racecar",
    "sampleOutput": "Yes\n",
    "testCases": [
      {
        "stdin": "hello",
        "expectedOutput": "No\n"
      },
      {
        "stdin": "abba",
        "expectedOutput": "Yes\n"
      },
      {
        "stdin": "a",
        "expectedOutput": "Yes\n"
      }
    ]
  },
  {
    "id": "count-words",
    "title": "Count Words",
    "description": "Read a line of text and print how many words it contains (words are separated by spaces).",
    "difficulty": "medium",
    "starterCode": "// Count Words\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "the quick brown fox",
    "sampleOutput": "4\n",
    "testCases": [
      {
        "stdin": "hello",
        "expectedOutput": "1\n"
      },
      {
        "stdin": "a b c d e",
        "expectedOutput": "5\n"
      },
      {
        "stdin": "one",
        "expectedOutput": "1\n"
      }
    ]
  },
  {
    "id": "second-largest",
    "title": "Second Largest",
    "description": "Read a line of space-separated integers and print the second largest distinct value.",
    "difficulty": "medium",
    "starterCode": "// Second Largest\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "3 1 4 1 5",
    "sampleOutput": "4\n",
    "testCases": [
      {
        "stdin": "10 20 30",
        "expectedOutput": "20\n"
      },
      {
        "stdin": "5 5 4",
        "expectedOutput": "4\n"
      },
      {
        "stdin": "9 8 7 6",
        "expectedOutput": "8\n"
      }
    ]
  },
  {
    "id": "sum-of-digits",
    "title": "Sum of Digits",
    "description": "Read a non-negative integer and print the sum of its digits.",
    "difficulty": "medium",
    "starterCode": "// Sum of Digits\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "1234",
    "sampleOutput": "10\n",
    "testCases": [
      {
        "stdin": "9999",
        "expectedOutput": "36\n"
      },
      {
        "stdin": "100",
        "expectedOutput": "1\n"
      },
      {
        "stdin": "5",
        "expectedOutput": "5\n"
      }
    ]
  },
  {
    "id": "fizzbuzz",
    "title": "FizzBuzz",
    "description": "Read n and print numbers 1..n, one per line. Print \"Fizz\" for multiples of 3, \"Buzz\" for multiples of 5, and \"FizzBuzz\" for multiples of both.",
    "difficulty": "medium",
    "starterCode": "// FizzBuzz\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "5",
    "sampleOutput": "1\n2\nFizz\n4\nBuzz\n",
    "testCases": [
      {
        "stdin": "15",
        "expectedOutput": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n"
      },
      {
        "stdin": "3",
        "expectedOutput": "1\n2\nFizz\n"
      },
      {
        "stdin": "1",
        "expectedOutput": "1\n"
      }
    ]
  },
  {
    "id": "binary-to-decimal",
    "title": "Binary to Decimal",
    "description": "Read a binary string (only 0s and 1s) and print its decimal value.",
    "difficulty": "medium",
    "starterCode": "// Binary to Decimal\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "1010",
    "sampleOutput": "10\n",
    "testCases": [
      {
        "stdin": "1111",
        "expectedOutput": "15\n"
      },
      {
        "stdin": "100000",
        "expectedOutput": "32\n"
      },
      {
        "stdin": "1",
        "expectedOutput": "1\n"
      }
    ]
  },
  {
    "id": "sort-ascending",
    "title": "Sort Ascending",
    "description": "Read a line of space-separated integers and print them sorted in ascending order, space-separated.",
    "difficulty": "hard",
    "starterCode": "// Sort Ascending\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "5 3 8 1",
    "sampleOutput": "1 3 5 8\n",
    "testCases": [
      {
        "stdin": "10 -2 3 -5",
        "expectedOutput": "-5 -2 3 10\n"
      },
      {
        "stdin": "1 1 2",
        "expectedOutput": "1 1 2\n"
      },
      {
        "stdin": "9 8 7 6 5",
        "expectedOutput": "5 6 7 8 9\n"
      }
    ]
  },
  {
    "id": "count-primes",
    "title": "Count Primes",
    "description": "Read an integer n and print how many prime numbers are less than or equal to n.",
    "difficulty": "hard",
    "starterCode": "// Count Primes\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "10",
    "sampleOutput": "4\n",
    "testCases": [
      {
        "stdin": "2",
        "expectedOutput": "1\n"
      },
      {
        "stdin": "30",
        "expectedOutput": "10\n"
      },
      {
        "stdin": "1",
        "expectedOutput": "0\n"
      },
      {
        "stdin": "100",
        "expectedOutput": "25\n"
      }
    ]
  },
  {
    "id": "longest-word",
    "title": "Longest Word",
    "description": "Read a line of text and print the longest word. If several words tie, print the first one.",
    "difficulty": "hard",
    "starterCode": "// Longest Word\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "the quick brown fox jumps",
    "sampleOutput": "quick\n",
    "testCases": [
      {
        "stdin": "i love programming",
        "expectedOutput": "programming\n"
      },
      {
        "stdin": "a bb ccc",
        "expectedOutput": "ccc\n"
      },
      {
        "stdin": "same size here",
        "expectedOutput": "same\n"
      }
    ]
  },
  {
    "id": "anagram-check",
    "title": "Anagram Check",
    "description": "Read two words (space-separated) and print \"Yes\" if they are anagrams of each other, otherwise \"No\".",
    "difficulty": "hard",
    "starterCode": "// Anagram Check\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "listen silent",
    "sampleOutput": "Yes\n",
    "testCases": [
      {
        "stdin": "hello world",
        "expectedOutput": "No\n"
      },
      {
        "stdin": "abc cab",
        "expectedOutput": "Yes\n"
      },
      {
        "stdin": "aabb bbaa",
        "expectedOutput": "Yes\n"
      }
    ]
  },
  {
    "id": "fibonacci-sequence",
    "title": "Fibonacci Sequence",
    "description": "Read n and print the first n Fibonacci numbers (starting 0 1), space-separated on one line.",
    "difficulty": "hard",
    "starterCode": "// Fibonacci Sequence\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "7",
    "sampleOutput": "0 1 1 2 3 5 8\n",
    "testCases": [
      {
        "stdin": "1",
        "expectedOutput": "0\n"
      },
      {
        "stdin": "10",
        "expectedOutput": "0 1 1 2 3 5 8 13 21 34\n"
      },
      {
        "stdin": "2",
        "expectedOutput": "0 1\n"
      }
    ]
  },
  {
    "id": "two-sum",
    "title": "Two Sum",
    "description": "Line 1 is the target. Line 2 is an array of space-separated integers. Print the two 0-based indices (space-separated) of the numbers that add up to the target. Exactly one solution exists.",
    "difficulty": "hard",
    "starterCode": "// Two Sum\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "9\n2 7 11 15",
    "sampleOutput": "0 1\n",
    "testCases": [
      {
        "stdin": "6\n3 2 4",
        "expectedOutput": "1 2\n"
      },
      {
        "stdin": "10\n1 5 5 3",
        "expectedOutput": "1 2\n"
      },
      {
        "stdin": "8\n1 2 3 4 5",
        "expectedOutput": "2 4\n"
      }
    ]
  },
  {
    "id": "most-frequent-char",
    "title": "Most Frequent Character",
    "description": "Read a string (ignoring spaces) and print the character that appears most often. If several tie, print the alphabetically smallest.",
    "difficulty": "hard",
    "starterCode": "// Most Frequent Character\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "banana",
    "sampleOutput": "a\n",
    "testCases": [
      {
        "stdin": "abcabc",
        "expectedOutput": "a\n"
      },
      {
        "stdin": "mississippi",
        "expectedOutput": "i\n"
      },
      {
        "stdin": "aabbbcc",
        "expectedOutput": "b\n"
      }
    ]
  },
  {
    "id": "balanced-parentheses",
    "title": "Balanced Parentheses",
    "description": "Read a string of brackets ( ) [ ] { } and print \"Yes\" if they are balanced and correctly nested, otherwise \"No\".",
    "difficulty": "hard",
    "starterCode": "// Balanced Parentheses\n// Read all input from stdin, compute the answer, and print it with console.log.\nconst input = require('fs').readFileSync(0, 'utf8').trim();\n\n// TODO: write your solution here\n",
    "language": "javascript",
    "sampleInput": "([])",
    "sampleOutput": "Yes\n",
    "testCases": [
      {
        "stdin": "([)]",
        "expectedOutput": "No\n"
      },
      {
        "stdin": "(())",
        "expectedOutput": "Yes\n"
      },
      {
        "stdin": "((",
        "expectedOutput": "No\n"
      },
      {
        "stdin": "{[()]}",
        "expectedOutput": "Yes\n"
      }
    ]
  }
];

export const CODE_QUESTION_INDEX = new Map(CODE_QUESTIONS.map((question) => [question.id, question]));
